name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        required: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
  
      - name: Clone Repo
        run: | 
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
          cd ${{ github.event.repository.name }}
          git branch -a
