name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        required: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
  
      - name: Clone Repo
        run: | 
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
          cd ${{ github.event.repository.name }}

      - name: Create release branch
        run: | 
          git checkout develop
          git checkout -b release/${{ github.event.inputs.version }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
          git fetch --all

      - name: Bump version in package.json
        run: yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Commit files
        id: make-commit
        run: |
          git add .
          git commit --message "Prepare release ${{ github.event.inputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
          
      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.version }}

      - name: Update main
        run: | 
          git checkout main
          git merge --no-ff release/${{ github.event.inputs.version }} 
          git tag -a ${{ github.event.inputs.version }} -m ${{ github.event.inputs.version }}
          git push origin main
          