name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Gitflow
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
          
          git checkout develop
          
          git add .
          git commit -m release-2.0.0
          
          git push --all
          
          git checkout -b release-2.0.0 develop
          git checkout main
          git merge --no-ff release-2.0.0
          git tag -a 2.0.0 -m 2.0.0
          
          git push --all
          git push origin --tags
          
          git checkout develop
          git merge --no-ff release-2.0.0
          
          git push --all
          
          git branch -d release-2.0.0
          git push origin --delete release-2.0.0
