name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        required: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
  
      - name: Clone Repo
        run: | 
          git clone https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
      - name: Update Package Version
        run: | 
          cd ${{ github.event.repository.name }}
          git checkout develop
          yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version
      - name: Gitflow
        run: |
          cd ${{ github.event.repository.name }}
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
          git config --global credential.helper "/bin/sh ./.git_creds.sh"
          echo '#!/bin/sh' > ./.git_creds.sh
          echo "sleep 1" >> ./.git_creds.sh
          echo "echo username=${{ github.repository_owner }}" >> ./.git_creds.sh
          echo "echo password=${{ secrets.GITHUB_TOKEN }}" >> ./.git_creds.sh
          echo .git_creds.sh >> .git/info/exclude
          echo pom.xml.versionsBackup >> .git/info/exclude
          git config --global --add safe.directory '*'
          git fetch --all
          
          git checkout develop
          git add .
          git commit -m release-${artifactVersion}
          git push --all
          git checkout -b release/${{ github.event.inputs.version }}
          
          git checkout main
          git merge --no-ff release/${{ github.event.inputs.version }}
          git tag -a ${{ github.event.inputs.version }} -m ${{ github.event.inputs.version }}
          git push --all
          git push origin --tags
          git checkout develop
          git merge --no-ff release/${{ github.event.inputs.version }}
          git push --all
          git branch -d release/${{ github.event.inputs.version }}
          git push origin --delete release/${{ github.event.inputs.version }}
